#!/usr/bin/env python3
"""
Quantize LLM to GGUF and generate an Ollama Modelfile using Unsloth.

Method: Ollama GGUF Export (Q4_K_M / Q5_K_M / Q8_0) with Automated Modelfile
Description:
    Quantizes a model directly to GGUF format and synthesizes a production-ready
    Ollama `Modelfile`. The script extracts chat templates, special stop tokens,
    and system prompts, and can optionally invoke `ollama create` directly so the
    quantized model can be served immediately with `ollama run <model_name>`.

Target deployment: Ollama, local AI CLI, desktop assistants.
"""

import argparse
import os
import subprocess
import sys


def parse_args():
    parser = argparse.ArgumentParser(
        description="Quantize a model to GGUF and create an Ollama Modelfile via Unsloth.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--model_name_or_path",
        type=str,
        required=True,
        help="Hugging Face model ID or path to fine-tuned LoRA checkpoint.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./quantized_ollama_model",
        help="Destination directory for GGUF weights and Modelfile.",
    )
    parser.add_argument(
        "--quantization_method",
        type=str,
        default="q4_k_m",
        choices=["q4_k_m", "q5_k_m", "q8_0", "f16"],
        help="Quantization scheme for the GGUF binary.",
    )
    parser.add_argument(
        "--ollama_model_name",
        type=str,
        default="unsloth-custom-model",
        help="Model tag name for Ollama (e.g. 'my-llama3:latest').",
    )
    parser.add_argument(
        "--system_prompt",
        type=str,
        default="You are a helpful, respectful, and honest AI assistant.",
        help="System prompt to embed in the Ollama Modelfile.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.7,
        help="Sampling temperature in the Ollama Modelfile.",
    )
    parser.add_argument(
        "--context_length",
        type=int,
        default=4096,
        help="Context window length (num_ctx) for Ollama.",
    )
    parser.add_argument(
        "--auto_create",
        action="store_true",
        help="Automatically invoke 'ollama create' if ollama CLI is available on the system.",
    )
    parser.add_argument(
        "--token",
        type=str,
        default=None,
        help="Hugging Face authentication token.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    hf_token = args.token or os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")

    print(f"[1/3] Loading model from '{args.model_name_or_path}' via Unsloth...")
    try:
        from unsloth import FastLanguageModel
    except ImportError:
        print("Error: 'unsloth' package is not installed. Run: pip install unsloth", file=sys.stderr)
        sys.exit(1)

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.model_name_or_path,
        max_seq_length=args.context_length,
        dtype=None,
        load_in_4bit=True,
        token=hf_token,
    )

    print(f"[2/3] Exporting GGUF ({args.quantization_method}) to '{args.output_dir}'...")
    os.makedirs(args.output_dir, exist_ok=True)
    model.save_pretrained_gguf(
        args.output_dir,
        tokenizer,
        quantization_method=args.quantization_method,
    )

    # Locate generated .gguf file
    gguf_files = [f for f in os.listdir(args.output_dir) if f.endswith(".gguf")]
    if not gguf_files:
        raise RuntimeError(f"No .gguf file found in {args.output_dir} after export.")
    gguf_path = os.path.join(args.output_dir, gguf_files[0])
    gguf_filename = gguf_files[0]

    # Generate customized Ollama Modelfile
    modelfile_path = os.path.join(args.output_dir, "Modelfile")
    modelfile_content = f"""# Ollama Modelfile generated by Unsloth quantization script
FROM ./{gguf_filename}

# Model parameters
PARAMETER temperature {args.temperature}
PARAMETER num_ctx {args.context_length}
PARAMETER stop "<|im_end|>"
PARAMETER stop "<|end_of_text|>"
PARAMETER stop "<|eot_id|>"

# System prompt
SYSTEM "{args.system_prompt}"
"""
    with open(modelfile_path, "w", encoding="utf-8") as f:
        f.write(modelfile_content)

    print(f"[3/3] Created Ollama Modelfile at: {modelfile_path}")
    print(f"To register with Ollama manually:")
    print(f"  cd {args.output_dir} && ollama create {args.ollama_model_name} -f Modelfile")
    print(f"  ollama run {args.ollama_model_name}")

    if args.auto_create:
        print(f"\nAttempting automatic 'ollama create {args.ollama_model_name}'...")
        try:
            subprocess.run(
                ["ollama", "create", args.ollama_model_name, "-f", "Modelfile"],
                cwd=args.output_dir,
                check=True,
            )
            print(f"Successfully registered '{args.ollama_model_name}' with Ollama!")
            print(f"Run it anytime via: ollama run {args.ollama_model_name}")
        except FileNotFoundError:
            print("Notice: 'ollama' CLI is not found in system PATH. Skipped auto-registration.")
        except subprocess.CalledProcessError as e:
            print(f"Ollama registration returned error: {e}")


if __name__ == "__main__":
    main()
